function chatsPage(){const ps=activeProjects().map(p=>{const msgs=db.chat.filter(m=>m.projectId===p.id).sort((a,b)=>b.at.localeCompare(a.at));return {p,last:msgs[0],count:msgs.length}}).sort((a,b)=>(b.last?.at||'').localeCompare(a.last?.at||''));return `${pageHead('Chat','Alle Projektchats an einem Ort')}<div class="chat-inbox"><div class="chat-search">${ico('search')}<input placeholder="Projekt oder Nachricht suchen" oninput="filterChats(this.value)"></div><div id="chatInboxList">${ps.map(x=>`<article class="chat-inbox-row" data-search="${esc((x.p.name+' '+x.p.nr+' '+(x.last?.text||'')).toLowerCase())}" onclick="openProject('${x.p.id}','chat')"><div class="chat-project-avatar">${esc(x.p.name.slice(0,2).toUpperCase())}</div><div class="chat-inbox-main"><div class="chat-inbox-top"><strong>${esc(x.p.name)}</strong><time>${x.last?chatTime(x.last.at):''}</time></div><div class="chat-inbox-preview">${x.last?`<b>${esc(userName(x.last.userId))}:</b> ${esc(x.last.text||((x.last.attachments||[]).length?'Anhang':'Nachricht'))}`:'Noch keine Nachrichten'}</div><div class="chat-project-nr">${esc(x.p.nr)}</div></div><span class="chat-chevron">›</span></article>`).join('')}</div></div>`}
function chatTime(at){const d=new Date(at),now=new Date();return d.toDateString()===now.toDateString()?d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}
function filterChats(q){const s=(q||'').trim().toLowerCase();document.querySelectorAll('.chat-inbox-row').forEach(r=>r.style.display=!s||r.dataset.search.includes(s)?'':'none')}
function projectPage(){const p=project(view.projectId);if(!p||!canProject(p))return'<div class="card pad">Projekt nicht verfügbar.</div>';const tabs=isOffice()?[['overview','Übersicht'],['chat','Chat'],['tasks','Aufgaben'],['docs','Dokumente'],['material','Material'],['times','Zeiten'],['team','Mitarbeiter'],['contacts','Kontakte']]:[['overview','Übersicht'],['chat','Chat'],['tasks','Aufgaben'],['docs','Dokumente'],['material','Material'],['times','Zeiten']];return `<div class="project-mobile-head"><button class="project-back" onclick="go('${view.projectTab==='chat'?'chats':'projects'}')" aria-label="Zurück">‹</button><div><div class="project-mobile-name">${esc(p.name)}</div><div class="project-mobile-meta">${esc(p.nr)} · ${esc(p.status)}</div></div>${isOffice()?`<button class="project-info" onclick="projectForm('${p.id}')" aria-label="Projekt bearbeiten">ⓘ</button>`:'<span></span>'}</div>${pageHead(esc(p.name),`${esc(p.nr)} · ${esc(p.status)}`,isOffice()?`<button class="btn" onclick="projectForm('${p.id}')">${ico('edit')} Bearbeiten</button>`:'')}<div class="project-tabs">${tabs.map(([id,l])=>`<button class="${view.projectTab===id?'active':''}" onclick="setProjectTab('${id}')">${l}</button>`).join('')}</div>${renderProjectTab(p)}`}
function setProjectTab(t){view.projectTab=t;view.selectedFolder=null;render()}
function renderProjectTab(p){switch(view.projectTab){case'overview':return projectOverview(p);case'tasks':return projectTasks(p);case'chat':return projectChat(p);case'times':return projectTimes(p);case'team':return projectTeam(p);case'material':return projectMaterial(p);case'docs':return projectDocs(p);case'contacts':return projectContacts(p);default:return projectOverview(p)}}
function projectOverview(p){return `<div class="detail-grid"><div class="detail-card"><div class="label">Kunde / Firma</div><div class="value">${esc(p.customer||'–')}</div>${contactLinks(p.customerPhone,p.customerEmail)}</div><div class="detail-card"><div class="label">Ansprechpartner</div><div class="value">${esc(p.contact||'–')}</div>${contactLinks(p.contactPhone,p.contactEmail)}</div><div class="detail-card span2"><div class="label">Baustellenadresse</div><div class="value">${esc(p.address||'–')}</div></div></div>`}
function contactLinks(phone,email){if(!phone&&!email)return'<div class="small muted mt8">Keine Kontaktdaten hinterlegt</div>';return `<div class="contact-actions">${phone?`<a class="btn sm" href="tel:${esc(phone)}">${ico('phone')} ${esc(phone)}</a>`:''}${email?`<a class="btn sm" href="mailto:${esc(email)}">${ico('mail')} ${esc(email)}</a>`:''}</div>`}
function projectTasks(p){const ts=db.tasks.filter(t=>t.projectId===p.id&&(isOffice()||t.assignees.includes(user().id)));return `<div class="between"><h2 class="section-title">Aufgaben</h2>${isOffice()?`<button class="btn primary sm" onclick="taskForm(null,'${p.id}')">${ico('plus')} Aufgabe</button>`:''}</div>${taskTable(ts)}`}
function projectChat(p){const msgs=db.chat.filter(m=>m.projectId===p.id).sort((a,b)=>a.at.localeCompare(b.at));return `<div class="card pad chat"><div class="messages" id="messages">${msgs.map(m=>`<div class="msg ${m.userId===user().id?'me':''}"><div class="msg-head"><b>${esc(userName(m.userId))}</b><span>${new Date(m.at).toLocaleString('de-DE')}</span></div><div class="msg-text">${linkMentions(esc(m.text))}</div>${(m.attachments||[]).map(a=>a.data?`<div class="small mt8"><a class="linkbtn" href="${a.data}" download="${esc(a.name)}">📎 ${esc(a.name)}</a></div>`:'').join('')}</div>`).join('')}</div><div class="chat-compose"><textarea id="chatText" placeholder="Nachricht …"></textarea><label class="btn icon">📎<input type="file" hidden multiple onchange="addChatFiles(this.files)"></label><button class="btn icon" id="voiceBtn" onclick="toggleVoiceRecord()">🎙</button><button class="btn primary" onclick="sendChat('${p.id}')">Senden</button></div></div>`}
function linkMentions(t){return t.replace(/@([\wÄÖÜäöüß.-]+)/g,'<b style="color:#1d4ed8">@$1</b>')}
function sendChat(pid){const tx=document.getElementById('chatText').value.trim();if(!tx&&!chatPending.length)return;db.chat.push({id:uid('m'),projectId:pid,userId:user().id,text:tx,at:new Date().toISOString(),pinned:false,attachments:chatPending});chatPending=[];save();render()}
function togglePin(id){const m=db.chat.find(x=>x.id===id);m.pinned=!m.pinned;save();render()}
