function timesPage(){const mk=monthKey(),me=user().id;const arr=db.timeEntries.filter(t=>(isOffice()||t.userId===me)&&t.date.startsWith(mk));const target=isOffice()?null:getTarget(me,mk),ist=arr.filter(t=>t.userId===me).reduce((s,x)=>s+Number(x.hours),0);return `${pageHead('Zeiten',isOffice()?'Monatliche Stundenübersicht ohne Start/Pause/Ende':'Deine Stunden einfach als Anzahl erfassen',`<button class="btn primary" onclick="timeForm()">${ico('plus')} Stunden erfassen</button>${isOffice()?`<button class="btn" onclick="exportTimesCSV()">CSV Export</button>`:''}`)}${!isOffice()?`<div class="grid three-col mb0"><div class="card kpi"><div class="label">Soll ${mk}</div><div class="num">${target} h</div></div><div class="card kpi"><div class="label">Ist</div><div class="num">${fmtNum(ist)} h</div></div><div class="card kpi"><div class="label">Saldo</div><div class="num">${fmtNum(ist-target)} h</div></div></div><div class="mt16"></div>`:''}${isOffice()?monthlyEmployeeOverview(mk):timeTable(arr)}${isOffice()?`<div class="card pad mt16"><div class="between"><h2 class="section-title">Monatsabschluss</h2><button class="btn primary sm" onclick="closeMonth('${mk}')">Monat ${mk} abschließen</button></div><div class="small muted">Beim Abschluss werden Soll und Saldo festgeschrieben. Mitarbeiter können geschlossene Monate nicht mehr ändern.</div></div>`:''}`}
function monthlyEmployeeOverview(mk){return `<div class="table-wrap"><table class="table"><thead><tr><th>Mitarbeiter</th><th>Soll</th><th>Ist</th><th>Monatssaldo</th><th>Überstunden gesamt</th><th>Urlaub Rest</th><th>Aktion</th></tr></thead><tbody>${db.users.filter(u=>u.active&&u.role==='employee').map(u=>{const ist=db.timeEntries.filter(t=>t.userId===u.id&&t.date.startsWith(mk)).reduce((s,x)=>s+Number(x.hours),0),target=getTarget(u.id,mk);return `<tr><td><b>${esc(u.first+' '+u.last)}</b></td><td>${target} h</td><td>${fmtNum(ist)} h</td><td>${fmtNum(ist-target)} h</td><td>${fmtNum(overtimeTotal(u.id))} h</td><td>${vacationStats(u.id).remaining}</td><td><button class="btn sm" onclick="targetForm('${u.id}','${mk}')">Soll ändern</button></td></tr>`}).join('')}</tbody></table></div>`}
function getTarget(uid,mk){const closure=db.monthClosures.find(c=>c.userId===uid&&c.month===mk);if(closure)return closure.target;return db.monthlyTargets[uid+'_'+mk]??176}
function overtimeTotal(uid){const closed=db.monthClosures.filter(c=>c.userId===uid).reduce((s,c)=>s+c.balance,0);const current=monthKey(),ist=db.timeEntries.filter(t=>t.userId===uid&&t.date.startsWith(current)).reduce((s,x)=>s+Number(x.hours),0);return closed+(db.monthClosures.some(c=>c.userId===uid&&c.month===current)?0:ist-getTarget(uid,current))}
function targetForm(uid,mk){openModal('Monatssoll ändern',`<div class="field"><label>${esc(userName(uid))} · ${mk}</label><input id="targetVal" type="number" step="0.5" value="${getTarget(uid,mk)}"></div>`,`<button class="btn" onclick="closeModal()">Abbrechen</button><button class="btn primary" onclick="saveTarget('${uid}','${mk}')">Speichern</button>`)}
async function saveTarget(uid,mk){db.monthlyTargets[uid+'_'+mk]=Number(v('targetVal')||176);await save();closeModal();render();toast('Monatssoll gespeichert')}
async function closeMonth(mk){const emps=db.users.filter(u=>u.active&&u.role==='employee');const missing=emps.filter(u=>db.allocations.some(a=>a.userId===u.id&&a.date.startsWith(mk))&&!db.timeEntries.some(t=>t.userId===u.id&&t.date.startsWith(mk)));if(missing.length&&!confirm(`Bei ${missing.map(x=>x.first).join(', ')} fehlen Stunden. Trotzdem abschließen?`))return;emps.forEach(u=>{if(db.monthClosures.some(c=>c.userId===u.id&&c.month===mk))return;const target=getTarget(u.id,mk),ist=db.timeEntries.filter(t=>t.userId===u.id&&t.date.startsWith(mk)).reduce((s,x)=>s+Number(x.hours),0);db.monthClosures.push({id:uid('mc'),userId:u.id,month:mk,target,actual:ist,balance:ist-target,closedAt:new Date().toISOString(),closedBy:user().id})});await save();render();toast('Monat abgeschlossen')}
function isMonthClosed(uid,mk){return db.monthClosures.some(c=>c.userId===uid&&c.month===mk)}
function timeForm(pid=null){const pids=activeProjects();openModal('Stunden erfassen',`<div class="form-grid"><div class="field"><label>Mitarbeiter</label><select id="timeUser" ${!isOffice()?'disabled':''}>${db.users.filter(u=>u.active&&u.role==='employee'||u.id===user().id).map(u=>`<option value="${u.id}" ${u.id===user().id?'selected':''}>${esc(u.first+' '+u.last)}</option>`).join('')}</select></div><div class="field"><label>Projekt</label><select id="timeProject">${pids.map(p=>`<option value="${p.id}" ${p.id===pid?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Datum *</label><input id="timeDate" type="date" value="${today()}"></div><div class="field"><label>Stunden *</label><input id="timeHours" type="number" min="0.25" max="24" step="0.25" value="8"></div><div class="field span2"><label>Tätigkeit</label><input id="timeActivity" placeholder="z. B. Trockenbau"></div><div class="field span2"><label>Notiz</label><textarea id="timeNote"></textarea></div></div>`,`<button class="btn" onclick="closeModal()">Abbrechen</button><button class="btn primary" onclick="saveTime()">Speichern</button>`)}
async function saveTime(){const uidv=v('timeUser'),date=v('timeDate'),hours=Number(v('timeHours'));if(!date||!hours)return toast('Datum und Stunden fehlen','err');if(!isOffice()&&isMonthClosed(uidv,monthKey(date)))return toast('Dieser Monat ist abgeschlossen','err');db.timeEntries.push({id:uid('te'),userId:uidv,projectId:v('timeProject'),date,hours,activity:v('timeActivity'),note:v('timeNote')});await save();closeModal();render();toast('Stunden gespeichert')}

