function seed(){const admin='u_admin',ivan='u_ivan',marko='u_marko';return {company:{id:'org1',name:'',logo:'',address:'',phone:'',email:'',accent:'#2563eb'},users:[{id:admin,first:'Ion',last:'Admin',email:'admin@ionbau.local',phone:'',role:'admin',active:true,password:'admin',entry:'2026-01-01',vacationAnnual:30,notes:''},{id:ivan,first:'Ivan',last:'Petrovic',email:'ivan@ionbau.local',phone:'0151 11111111',role:'employee',active:true,password:'ivan',entry:'2026-01-15',vacationAnnual:30,notes:''},{id:marko,first:'Marko',last:'Perkovic',email:'marko@ionbau.local',phone:'0151 22222222',role:'office',active:true,password:'marko',entry:'2026-01-01',vacationAnnual:30,notes:''}],session:null,projects:[{id:'p1',nr:'2026-041',name:'Goldstein',customer:'Beispielkunde GmbH',customerPhone:'069 1234567',customerEmail:'bau@beispielkunde.de',contact:'Herr Müller',contactPhone:'0171 5552211',contactEmail:'mueller@beispielkunde.de',address:'Musterstraße 10, Frankfurt am Main',start:'2026-09-07',end:'2026-10-02',status:'In Ausführung',note:'Zugang über Hof. Schlüsselkasten neben Seiteneingang.',workStart:'07:00',members:[admin,ivan,marko],archived:false,folders:folders.map((n,i)=>({id:'f1_'+i,name:n,employeeVisible:i>=6,files:[]}))},{id:'p2',nr:'2026-042',name:'Kelkheim',customer:'Muster WEG',customerPhone:'',customerEmail:'',contact:'Frau Lelek',contactPhone:'',contactEmail:'',address:'Kelkheim',start:'2026-09-14',end:'2026-09-18',status:'Restarbeiten',note:'',workStart:'07:30',members:[admin,ivan],archived:false,folders:folders.map((n,i)=>({id:'f2_'+i,name:n,employeeVisible:i>=6,files:[]}))}],tasks:[{id:'t1',projectId:'p1',title:'Elektriker Fragen klären',category:'Büro',assignees:[admin],due:'2026-09-14',priority:'Hoch',status:'Offen',description:'Offene Punkte vor Ausführung klären.',comments:[],history:[{at:new Date().toISOString(),by:admin,text:'Aufgabe angelegt'}],attachments:[]}],chat:[{id:'m1',projectId:'p1',userId:marko,text:'Materiallieferung kommt Montag um 08:00 Uhr.',at:'2026-09-13T10:00:00',pinned:true,attachments:[]}],timeEntries:[{id:'te1',userId:ivan,projectId:'p1',date:'2026-09-12',hours:8,activity:'Trockenbau',note:''}],monthlyTargets:{},monthClosures:[],absences:[],allocations:[{id:'a1',userId:ivan,projectId:'p1',date:'2026-09-14',hours:8,note:''}],phases:[{id:'ph1',projectId:'p1',name:'Trockenbau',start:'2026-09-14',end:'2026-09-18',required:2,status:'Geplant'},{id:'ph2',projectId:'p1',name:'Spachteln',start:'2026-09-21',end:'2026-09-25',required:2,status:'Geplant'},{id:'ph3',projectId:'p2',name:'Restarbeiten',start:'2026-09-14',end:'2026-09-18',required:1,status:'Geplant'}],materials:[{id:'mr1',projectId:'p1',requestedBy:ivan,needed:'2026-09-15',note:'Bitte morgens liefern.',items:[{name:'CW 75 Profil',qty:20,unit:'Stk'},{name:'GKBI',qty:45,unit:'m²'}],status:'Angefordert',supplier:'',delivery:'',orderNo:'',officeNote:'',createdAt:'2026-09-13T09:00:00'}],notifications:[],audit:[]};}
function extraDemoProjects(){const members=['u_admin','u_ivan','u_marko'];const data=[
['p3','2026-043','KKG – Erweiterungsbau Kindergarten','Katholische Kirchengemeinde','Frankfurt am Main','2026-09-10','2026-10-30','In Ausführung'],
['p4','2026-044','Rüsselsheim – Robert-Bunsen-Straße 37','Baugesellschaft Rhein-Main','Rüsselsheim am Main','2026-08-24','2026-09-25','Restarbeiten'],
['p5','2026-045','Sachsenhausen – Dachterrasse','Privatkunde','Frankfurt-Sachsenhausen','2026-09-17','2026-09-30','Geplant'],
['p6','2026-046','Tiny House – Innenausbau','BWW Projektbau','Frankfurt am Main','2026-09-21','2026-10-09','Geplant'],
['p7','2026-047','Contora Office Solutions','Contora AG','Frankfurt am Main','2026-09-14','2026-10-16','In Ausführung'],
['p8','2026-048','Heinestraße – Innenputz','Wohnbau Rhein-Main','Frankfurt am Main','2026-08-17','2026-09-18','Restarbeiten'],
['p9','2026-049','Passavantenstraße – Sanierung','Privatkunde','Frankfurt am Main','2026-08-31','2026-09-25','In Ausführung'],
['p10','2026-050','Dossenheim – Ausbauarbeiten','Projektentwicklung Süd','Dossenheim','2026-10-05','2026-11-06','Vorbereitung'],
['p11','2026-051','Ober-Ramstadt – Trockenbau F90','Industriebau Rhein-Main','Ober-Ramstadt','2026-09-28','2026-10-23','Geplant'],
['p12','2026-052','ATREEUM – Büroausbau','ATREEUM Projekt GmbH','Frankfurt am Main','2026-08-03','2026-09-18','Restarbeiten'],
['p13','2026-053','Dornbusch – WDVS Fassade','WEG Dornbusch','Frankfurt-Dornbusch','2026-09-07','2026-10-23','In Ausführung'],
['p14','2026-054','Bischoffsheim – Fenstermontage','MP Projektentwicklung GmbH','Maintal','2026-09-22','2026-10-02','Geplant'],
['p15','2026-055','Cretzschmarstraße – Ausbau','MainCon GmbH','Frankfurt am Main','2026-10-12','2026-11-13','Vorbereitung'],
['p16','2026-056','Nied – Maler- und Spachtelarbeiten','Nova Ausbau GmbH','Frankfurt-Nied','2026-09-14','2026-09-25','In Ausführung'],
['p17','2026-057','Tiefgarage – Sockelbekleidung','WEG Verwaltung Frankfurt','Frankfurt am Main','2026-08-10','2026-09-18','Restarbeiten'],
['p18','2026-058','Goldstein – Wiesenhof Restleistungen','Wohnbau Goldstein','Frankfurt-Goldstein','2026-09-16','2026-09-30','Geplant']
];return data.map((x,idx)=>({id:x[0],nr:x[1],name:x[2],customer:x[3],customerPhone:'',customerEmail:'',contact:'',contactPhone:'',contactEmail:'',address:x[4],start:x[5],end:x[6],status:x[7],note:'',workStart:'07:00',members:[...members],archived:false,folders:folders.map((n,i)=>({id:`${x[0]}_f${i}`,name:n,employeeVisible:i>=6,files:[]}))}));}
let db;let chatPending=[];let materialPending=null;let absencePending=null;let mediaRecorder=null;let mediaChunks=[];let view={page:'dashboard',projectId:null,projectTab:'overview',taskFilter:'all',weekAnchor:today(),selectedFolder:null,search:''};
function load(){try{db=JSON.parse(localStorage.getItem(STORE_KEY))||seed()}catch(e){db=seed()}migrate();}
async function migrate(){db.company=db.company||seed().company;db.users=db.users||[];db.projects=db.projects||[];db.tasks=db.tasks||[];db.chat=db.chat||[];db.timeEntries=db.timeEntries||[];db.monthlyTargets=db.monthlyTargets||{};db.monthClosures=db.monthClosures||[];db.absences=db.absences||[];db.allocations=db.allocations||[];db.phases=db.phases||[];db.materials=db.materials||[];db.notifications=db.notifications||[];db.audit=db.audit||[];const extras=extraDemoProjects();extras.forEach(p=>{if(!db.projects.some(x=>x.id===p.id||x.nr===p.nr))db.projects.push(p)});db.projects.forEach(p=>{p.members=p.members||[];p.folders=p.folders||folders.map((n,i)=>({id:uid('f'),name:n,employeeVisible:i>=6,files:[]}));});await save();}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(db))}
function user(){return db.users.find(x=>x.id===db.session?.userId)}
function role(){return user()?.role||''}
function isAdmin(){return role()==='admin'}function isOffice(){return ['admin','office'].includes(role())}
function userName(id){const u=db.users.find(x=>x.id===id);return u?`${u.first} ${u.last}`:'Unbekannt'}
function project(id){return db.projects.find(x=>x.id===id)}
function canProject(p){return isOffice()||p.members.includes(user()?.id)}
function toast(msg,type='ok'){const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;document.getElementById('toastRoot').appendChild(el);setTimeout(()=>el.remove(),2600)}
function openModal(title,body,foot='',wide=false){document.body.classList.add('modal-open');document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal ${wide?'wide':''}"><div class="modal-head"><h2>${title}</h2><button class="xbtn" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div>${foot?`<div class="modal-foot">${foot}</div>`:''}</div></div>`}
function closeModal(){document.body.classList.remove('modal-open');document.getElementById('modalRoot').innerHTML=''}
async function audit(action,entity,id){db.audit.unshift({id:uid('au'),at:new Date().toISOString(),userId:user()?.id,action,entity,entityId:id});await save()}
function statusPill(s){let c=['In Ausführung','Erledigt','Geliefert','Genehmigt'].includes(s)?'green':['Überfällig','Abgelehnt','Storniert'].includes(s)?'red':['Hoch','Unterwegs','Krank'].includes(s)?'orange':['Geplant','Bestellt','In Arbeit'].includes(s)?'blue':'gray';return `<span class="pill ${c}">${esc(s)}</span>`}
