function navItems(){if(isOffice())return [['dashboard','Dashboard','dashboard'],['projects','Projekte','projects'],['siteplan','Baustellenplanung','siteplan'],['planning','Mitarbeiterplanung','planning'],['tasks','Aufgaben','tasks'],['times','Zeiten','time'],['employees','Mitarbeiter','people'],['materials','Material','material']].concat(isAdmin()?[['settings','Einstellungen','settings']]:[]);return [['dashboard','Heute','dashboard'],['projects','Projekte','projects'],['tasks','Aufgaben','tasks'],['times','Zeiten','time'],['materials','Material','material'],['me','Mein Bereich','people']];}
function companyBrand(){const name=db.company.name||'Unternehmen einrichten';const initials=name==='Unternehmen einrichten'?'IB':name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();return `<div class="brand-card"><div class="brand-logo">${db.company.logo?`<img src="${db.company.logo}" alt="Logo">`:`<span class="initials">${esc(initials)}</span>`}</div><div><div class="brand-title">${esc(name)}</div><div class="product-mark">Powered by ION BAU</div></div></div>`}
function render(){if(!db.session||!user()||!user().active)return renderLogin();const u=user();const nav=navItems();document.getElementById('app').innerHTML=`<div class="shell"><aside class="sidebar" id="sidebar">${companyBrand()}<nav class="nav">${nav.map(([p,l,i])=>`<button class="${view.page===p?'active':''}" onclick="go('${p}')">${ico(i)}<span>${l}</span></button>`).join('')}</nav><div class="sidebar-bottom"><div class="user-mini">${esc(u.first+' '+u.last)}</div><div class="small">${roleLabel(u.role)}</div><button class="logout-link" onclick="logout()">Abmelden</button><div class="product-mark">ION BAU · ${VERSION}</div></div></aside><main class="main"><header class="topbar"><div class="flex gap8" style="align-items:center;flex:1"><button class="hamburger" onclick="toggleSidebar()">${ico('menu')}</button><div class="searchbar">${ico('search')}<input id="globalSearch" placeholder="Projekte, Aufgaben, Kunden suchen …" value="${esc(view.search)}" onkeydown="if(event.key==='Enter')doSearch(this.value)"></div></div><button class="btn icon" onclick="notificationModal()" title="Benachrichtigungen" style="position:relative">${ico('bell')}${unreadNotifications()?`<span style="position:absolute;right:2px;top:2px;background:#d33f49;color:white;border-radius:999px;font-size:10px;min-width:17px;height:17px;display:grid;place-items:center">${unreadNotifications()}</span>`:''}</button><div class="user-chip"><div class="avatar">${esc(u.first[0])}</div><div class="user-txt"><div class="bold">${esc(u.first)}</div><div class="small muted">${roleLabel(u.role)}</div></div></div></header><div class="content" id="content">${renderPage()}</div></main></div>${mobileNav()}`;}
function mobileNav(){const items=isOffice()?[['dashboard','Heute','dashboard'],['projects','Projekte','projects'],['tasks','Aufgaben','tasks'],['planning','Planung','planning'],['materials','Material','material']]:[['dashboard','Heute','dashboard'],['tasks','Aufgaben','tasks'],['times','Zeiten','time'],['projects','Projekte','projects'],['me','Mehr','people']];return `<div class="bottom-mobile">${items.map(([p,l,i])=>`<button class="${view.page===p?'active':''}" onclick="go('${p}')">${ico(i)}<span>${l}</span></button>`).join('')}</div>`}
function renderLogin(){document.getElementById('app').innerHTML=`<div class="login-screen"><form class="login-card" onsubmit="login(event)"><div class="login-logo">ION</div><h1>ION BAU</h1><p>Interne Baustellen- und Projektsteuerung</p><div class="field"><label>E-Mail</label><input id="loginEmail" type="email" value="admin@ionbau.local" required></div><div class="field mt12"><label>Passwort</label><input id="loginPass" type="password" value="admin" required></div><button class="btn primary w100 mt16" type="submit">Anmelden</button><div class="card pad mt16" style="background:#f8fafc"><div class="small"><b>Testzugänge</b><br>Admin: admin@ionbau.local / admin<br>Büro: marko@ionbau.local / marko<br>Mitarbeiter: ivan@ionbau.local / ivan</div></div></form></div>`}
async function login(e){e.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase(),pass=document.getElementById('loginPass').value;const u=db.users.find(x=>x.email.toLowerCase()===email&&x.password===pass&&x.active);if(!u)return toast('Login nicht gültig','err');db.session={userId:u.id};await save();view.page='dashboard';render()}
async function logout(){db.session=null;await save();render()}
function toggleSidebar(){document.getElementById('sidebar')?.classList.toggle('open')}
function go(p){view.page=p;view.projectId=null;view.selectedFolder=null;document.getElementById('sidebar')?.classList.remove('open');render()}
function renderPage(){switch(view.page){case'dashboard':return dashboard();case'projects':return projectsPage();case'project':return projectPage();case'tasks':return tasksPage();case'employees':return employeesPage();case'settings':return settingsPage();case'times':return timesPage();case'planning':return planningPage();case'siteplan':return siteplanPage();case'materials':return materialsPage();case'me':return mePage();case'search':return searchPage();default:return dashboard()}}
function pageHead(title,sub='',actions=''){return `<div class="pagehead"><div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><div class="actions">${actions}</div></div>`}
function activeProjects(){return db.projects.filter(p=>!p.archived&&canProject(p))}
function overdueTasks(){return db.tasks.filter(t=>t.status!=='Erledigt'&&t.due&&t.due<today()&&(isOffice()||t.assignees.includes(user().id)))}

