function seed(){const admin='u_admin',ivan='u_ivan',marko='u_marko';return {company:{id:'org1',name:'',logo:'',address:'',phone:'',email:'',accent:'#2563eb'},users:[{id:admin,first:'Ion',last:'Admin',email:'admin@ionbau.local',phone:'',role:'admin',active:true,password:'admin',entry:'2026-01-01',vacationAnnual:30,notes:''},{id:ivan,first:'Ivan',last:'Petrovic',email:'ivan@ionbau.local',phone:'0151 11111111',role:'employee',active:true,password:'ivan',entry:'2026-01-15',vacationAnnual:30,notes:''},{id:marko,first:'Marko',last:'Perkovic',email:'marko@ionbau.local',phone:'0151 22222222',role:'office',active:true,password:'marko',entry:'2026-01-01',vacationAnnual:30,notes:''}],session:null,projects:[{id:'p1',nr:'2026-041',name:'Goldstein',customer:'Beispielkunde GmbH',customerPhone:'069 1234567',customerEmail:'bau@beispielkunde.de',contact:'Herr Müller',contactPhone:'0171 5552211',contactEmail:'mueller@beispielkunde.de',address:'Musterstraße 10, Frankfurt am Main',start:'2026-09-07',end:'2026-10-02',status:'In Ausführung',note:'Zugang über Hof. Schlüsselkasten neben Seiteneingang.',workStart:'07:00',members:[admin,ivan,marko],archived:false,folders:folders.map((n,i)=>({id:'f1_'+i,name:n,employeeVisible:i>=6,files:[]}))},{id:'p2',nr:'2026-042',name:'Kelkheim',customer:'Muster WEG',customerPhone:'',customerEmail:'',contact:'Frau Lelek',contactPhone:'',contactEmail:'',address:'Kelkheim',start:'2026-09-14',end:'2026-09-18',status:'Restarbeiten',note:'',workStart:'07:30',members:[admin,ivan],archived:false,folders:folders.map((n,i)=>({id:'f2_'+i,name:n,employeeVisible:i>=6,files:[]}))}],tasks:[{id:'t1',projectId:'p1',title:'Elektriker Fragen klären',category:'Büro',assignees:[admin],due:'2026-09-14',priority:'Hoch',status:'Offen',description:'Offene Punkte vor Ausführung klären.',comments:[],history:[{at:new Date().toISOString(),by:admin,text:'Aufgabe angelegt'}],attachments:[]}],chat:[{id:'m1',projectId:'p1',userId:marko,text:'Materiallieferung kommt Montag um 08:00 Uhr.',at:'2026-09-13T10:00:00',pinned:true,attachments:[]}],timeEntries:[{id:'te1',userId:ivan,projectId:'p1',date:'2026-09-12',hours:8,activity:'Trockenbau',note:''}],monthlyTargets:{},monthClosures:[],absences:[],allocations:[{id:'a1',userId:ivan,projectId:'p1',date:'2026-09-14',hours:8,note:''}],phases:[{id:'ph1',projectId:'p1',name:'Trockenbau',start:'2026-09-14',end:'2026-09-18',required:2,status:'Geplant'},{id:'ph2',projectId:'p1',name:'Spachteln',start:'2026-09-21',end:'2026-09-25',required:2,status:'Geplant'},{id:'ph3',projectId:'p2',name:'Restarbeiten',start:'2026-09-14',end:'2026-09-18',required:1,status:'Geplant'}],materials:[{id:'mr1',projectId:'p1',requestedBy:ivan,needed:'2026-09-15',note:'Bitte morgens liefern.',items:[{name:'CW 75 Profil',qty:20,unit:'Stk'},{name:'GKBI',qty:45,unit:'m²'}],status:'Angefordert',supplier:'',delivery:'',orderNo:'',officeNote:'',createdAt:'2026-09-13T09:00:00'}],notifications:[],audit:[]};}
let db;let chatPending=[];let materialPending=null;let absencePending=null;let mediaRecorder=null;let mediaChunks=[];let view={page:'dashboard',projectId:null,projectTab:'overview',taskFilter:'all',weekAnchor:today(),selectedFolder:null,search:''};
function load(){try{db=JSON.parse(localStorage.getItem(STORE_KEY))||seed()}catch(e){db=seed()}migrate();}
function migrate(){db.company=db.company||seed().company;db.users=db.users||[];db.projects=db.projects||[];db.tasks=db.tasks||[];db.chat=db.chat||[];db.timeEntries=db.timeEntries||[];db.monthlyTargets=db.monthlyTargets||{};db.monthClosures=db.monthClosures||[];db.absences=db.absences||[];db.allocations=db.allocations||[];db.phases=db.phases||[];db.materials=db.materials||[];db.notifications=db.notifications||[];db.audit=db.audit||[];db.projects.forEach(p=>{p.members=p.members||[];p.folders=p.folders||folders.map((n,i)=>({id:uid('f'),name:n,employeeVisible:i>=6,files:[]}));});}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(db))}
function user(){return db.users.find(x=>x.id===db.session?.userId)}
function role(){return user()?.role||''}
function isAdmin(){return role()==='admin'}function isOffice(){return ['admin','office'].includes(role())}
function userName(id){const u=db.users.find(x=>x.id===id);return u?`${u.first} ${u.last}`:'Unbekannt'}
function project(id){return db.projects.find(x=>x.id===id)}
function canProject(p){return isOffice()||p.members.includes(user()?.id)}
function toast(msg,type='ok'){const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;document.getElementById('toastRoot').appendChild(el);setTimeout(()=>el.remove(),2600)}
function openModal(title,body,foot='',wide=false){document.body.classList.add('modal-open');document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal ${wide?'wide':''}"><div class="modal-head"><h2>${title}</h2><button class="xbtn" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div>${foot?`<div class="modal-foot">${foot}</div>`:''}</div></div>`}
function closeModal(){document.body.classList.remove('modal-open');document.getElementById('modalRoot').innerHTML=''}
async function audit(action,entity,id){db.audit.unshift({id:uid('au'),at:new Date().toISOString(),userId:user()?.id,action,entity,entityId:id});await save()}
function statusPill(s){let c=['In Ausführung','Erledigt','Geliefert','Genehmigt'].includes(s)?'green':['Überfällig','Abgelehnt','Storniert'].includes(s)?'red':['Hoch','Unterwegs','Krank'].includes(s)?'orange':['Geplant','Bestellt','In Arbeit'].includes(s)?'blue':'gray';return `<span class="pill ${c}">${esc(s)}</span>`}

