/* Shared validation and calendar rules; used by browser and server. */
(function(root){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const fail=m=>{throw Error(m)};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&iso(new Date(s+'T12:00:00'))===s;
const range=(a,b)=>{if(!validDate(a)||!validDate(b)||b<a)fail('Gültigen Zeitraum eingeben (Ende nicht vor Beginn).');};
function days(a,b){range(a,b);let out=[],d=new Date(a+'T12:00:00');while(iso(d)<=b){out.push(iso(d));d.setDate(d.getDate()+1);if(out.length>3660)fail('Zeitraum maximal zehn Jahre.');}return out;}
function holidays(y){const a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=(h+l-7*m+114)%31+1;const easter=new Date(y,month-1,day,12);return new Set([`${y}-01-01`,`${y}-05-01`,`${y}-10-03`,`${y}-12-25`,`${y}-12-26`,...[-2,1,39,50,60].map(n=>{const x=new Date(easter);x.setDate(x.getDate()+n);return iso(x);})]);}
function working(d,state){const day=new Date(d+'T12:00:00').getDay();return day!==0&&day!==6&&!holidays(Number(d.slice(0,4))).has(d)&&!(state?.company?.extraHolidays||[]).includes(d);}
const activeAbs=a=>['Genehmigt','Gemeldet'].includes(a.status);
const absent=(s,u,d)=>s.absences.some(a=>a.userId===u&&activeAbs(a)&&a.start<=d&&a.end>=d);
function vacation(s,u,y){const set=new Set(),planned=new Set();for(const a of s.absences.filter(a=>a.userId===u&&a.type==='vacation'&&['Genehmigt','Beantragt'].includes(a.status))){for(const d of days(a.start,a.end))if(+d.slice(0,4)===+y&&working(d,s))(a.status==='Genehmigt'?set:planned).add(d);}const person=s.users.find(x=>x.id===u);const annual=person?.vacationByYear?.[y]??person?.vacationAnnual??0;return {used:set.size,planned:planned.size,remaining:annual-set.size};}
function attendance(s,p,d){return new Set(s.allocations.filter(a=>a.projectId===p&&a.date===d&&a.hours>0&&!absent(s,a.userId,d)&&s.users.some(u=>u.id===a.userId&&u.active)).map(a=>a.userId)).size;}
function credits(s,u,m){const dates=new Set();for(const a of s.absences.filter(a=>a.userId===u&&activeAbs(a)&&['vacation','sick'].includes(a.type)))for(const d of days(a.start,a.end))if(d.startsWith(m)&&working(d,s))dates.add(d);return [...dates].reduce((n,d)=>n+Math.max(0,(s.company.creditHours??8)-s.timeEntries.filter(t=>t.userId===u&&t.date===d).reduce((x,t)=>x+t.hours,0)),0);}
function validate(s){
if(!s||!s.company||typeof s.company!=='object')fail('Unternehmensdaten fehlen.');
for(const key of ['users','projects','tasks','chat','timeEntries','monthClosures','absences','allocations','phases','materials','notifications','audit']){if(!Array.isArray(s[key]))fail('Ungültige Datentabelle: '+key);const ids=new Set();for(const x of s[key]){if(!x||typeof x.id!=='string'||!/^[-a-zA-Z0-9_]{1,100}$/.test(x.id)||ids.has(x.id))fail('Ungültige oder doppelte ID in '+key);ids.add(x.id);}}
function num(n,min,max,label){if(!Number.isFinite(n)||n<min||n>max)fail(label+' ist ungültig.');}
const users=new Map(s.users.map(u=>[u.id,u])),projects=new Map(s.projects.map(p=>[p.id,p]));const emails=new Set(),numbers=new Set();
for(const u of s.users){if(!u.first?.trim()||!u.last?.trim()||!/^\S+@\S+\.\S+$/.test(u.email||''))fail('Name und gültige E-Mail erforderlich.');if(emails.has(u.email.toLowerCase()))fail('E-Mail bereits vergeben.');emails.add(u.email.toLowerCase());if(!['admin','office','employee'].includes(u.role)||typeof u.active!=='boolean')fail('Ungültige Rolle/Status.');num(u.vacationAnnual,0,366,'Urlaubsanspruch');if(u.vacationByYear)for(const n of Object.values(u.vacationByYear))num(n,0,366,'Jahresanspruch');}
if(!s.users.some(u=>u.active&&u.role==='admin'))fail('Mindestens ein aktiver Admin muss erhalten bleiben.');
for(const p of s.projects){if(!p.name?.trim()||!p.nr?.trim()||numbers.has(p.nr))fail('Projektname und eindeutige Projektnummer erforderlich.');numbers.add(p.nr);if(p.start||p.end)range(p.start,p.end);if(!Array.isArray(p.members)||p.members.some(id=>!users.has(id)))fail('Ungültige Projektmitglieder.');if(!Array.isArray(p.folders))fail('Dokumentordner fehlen.');for(const f of p.folders){if(!/^[-\w]+$/.test(f.id)||!Array.isArray(f.files))fail('Ungültiger Ordner.');}}
const reference=(x,userKey='userId')=>{if(!projects.has(x.projectId)||!users.has(x[userKey]))fail('Projekt oder Mitarbeiter fehlt.');};
const totals={};for(const t of s.timeEntries){reference(t);if(!validDate(t.date))fail('Ungültiges Buchungsdatum.');num(t.hours,.25,24,'Stunden');if(t.hours*4%1)fail('Stunden in Viertelstunden erfassen.');const k=t.userId+t.date;totals[k]=(totals[k]||0)+t.hours;if(totals[k]>24)fail('Mehr als 24 Stunden pro Tag.');}
for(const a of s.absences){if(!users.has(a.userId))fail('Mitarbeiter fehlt.');range(a.start,a.end);if(!['vacation','sick','free'].includes(a.type)||!['Genehmigt','Gemeldet','Beantragt','Abgelehnt','Storniert'].includes(a.status))fail('Ungültige Abwesenheit.');}
for(let i=0;i<s.absences.length;i++){const a=s.absences[i];if(!['Genehmigt','Gemeldet','Beantragt'].includes(a.status))continue;for(const b of s.absences.slice(i+1))if(a.userId===b.userId&&['Genehmigt','Gemeldet','Beantragt'].includes(b.status)&&a.start<=b.end&&b.start<=a.end)fail('Abwesenheiten überschneiden sich.');}
const planned={};for(const a of s.allocations){reference(a);if(!validDate(a.date))fail('Einsatzdatum fehlt.');num(a.hours,.25,24,'Einsatzstunden');if(a.hours*4%1)fail('Einsatzstunden in Viertelstunden erfassen.');if(!projects.get(a.projectId).members.includes(a.userId))fail('Mitarbeiter zuerst dem Projekt zuordnen.');const k=a.userId+a.date;planned[k]=(planned[k]||0)+a.hours;if(planned[k]>24)fail('Planung überschreitet 24 Stunden/Tag.');}
for(const p of s.phases){if(!projects.has(p.projectId)||!p.name?.trim())fail('Projekt und Phasenname erforderlich.');range(p.start,p.end);num(p.required,1,1000,'Personalbedarf');if(!Number.isInteger(p.required))fail('Personalbedarf muss ganzzahlig sein.');}
for(const t of s.tasks){if(!projects.has(t.projectId)||!t.title?.trim()||!Array.isArray(t.assignees)||!t.assignees.length)fail('Aufgabe, Projekt und Zuständige erforderlich.');if(t.assignees.some(u=>!projects.get(t.projectId).members.includes(u)))fail('Zuständige zuerst dem Projekt zuordnen.');if(t.due&&!validDate(t.due))fail('Ungültige Aufgabenfrist.');if(!['Offen','In Arbeit','Erledigt'].includes(t.status)||!Array.isArray(t.comments)||!Array.isArray(t.history)||!Array.isArray(t.attachments))fail('Ungültige Aufgabe.');}
for(const m of s.materials){reference(m,'requestedBy');if(!validDate(m.needed)||!Array.isArray(m.items)||!m.items.length)fail('Materialposition und Termin erforderlich.');for(const i of m.items){if(!i.name?.trim())fail('Materialname fehlt.');num(i.qty,.001,1e8,'Materialmenge');num(i.received??0,0,i.qty,'Gelieferte Menge');}if(!['Angefordert','Bestellt','Unterwegs','Teilgeliefert','Geliefert','Storniert'].includes(m.status))fail('Ungültiger Materialstatus.');}
for(const m of s.chat){reference(m);if(typeof m.text!=='string'||!Array.isArray(m.attachments))fail('Ungültige Nachricht.');}
for(const n of Object.values(s.monthlyTargets||{}))num(n,0,744,'Monatssoll');
for(const c of s.monthClosures){if(!users.has(c.userId)||!/^\d{4}-\d{2}$/.test(c.month))fail('Ungültiger Monatsabschluss.');num(c.target,0,744,'Monatssoll');}
// Reject executable markup carriers and untrusted URLs in every imported nested record.
function walk(x,key=''){if(key==='id'&&(typeof x!=='string'||!/^[-\w]{1,100}$/.test(x)))fail('Ungültige ID.');if(x&&typeof x==='object'){for(const [k,v] of Object.entries(x)){if(['__proto__','constructor','prototype'].includes(k))fail('Ungültiger Schlüssel.');walk(v,k);}}else if(typeof x==='string'){if(x.length>3000000)fail('Text zu groß.');if(key==='id'&&!/^[-\w]{1,100}$/.test(x))fail('Ungültige ID.');if(['data','logo'].includes(key)&&x&&!/^\/api\/file\?id=[-\w]+$/.test(x)&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(x))fail('Ungültiger Datei-Verweis.');}}walk(s);
for(const p of s.projects)for(const f of p.folders){if(typeof f.name!=='string'||typeof f.employeeVisible!=='boolean')fail('Ungültiger Dokumentordner.');for(const file of f.files)if(typeof file.name!=='string'||typeof file.type!=='string'||!users.has(file.userId)||!Number.isFinite(file.size))fail('Ungültige Datei.');}
for(const t of s.tasks){for(const c of t.comments)if(typeof c.text!=='string'||!users.has(c.userId))fail('Ungültiger Kommentar.');for(const a of t.attachments)if(typeof a.name!=='string'||typeof a.data!=='string')fail('Ungültiger Anhang.');}
for(const m of s.chat)for(const a of m.attachments)if(typeof a.name!=='string'||typeof a.data!=='string')fail('Ungültiger Chat-Anhang.');
if(s.company.creditHours!==undefined)num(s.company.creditHours,0,24,'Tagesgutschrift');
if(s.company.extraHolidays&&(!Array.isArray(s.company.extraHolidays)||s.company.extraHolidays.some(d=>!validDate(d))))fail('Ungültige Feiertage.');
return s;
}
const api={clone,iso,validDate,range,days,working,holidays,absent,vacation,attendance,credits,validate};if(typeof module!=='undefined')module.exports=api;else root.Domain=api;
})(typeof window!=='undefined'?window:this);
