/* V1.1: server persistence, workflows, accessible UI. Loaded after legacy views. */
let revision=0,confirmed=null,saving=false,dirty=false,returnFocus=null,modalToken=0;
let editingTime=null,editingAllocation=null,editingPhase=null,editingAbsence=null;
const drafts=new Map();view.month=monthKey();view.year=new Date().getFullYear();view.materialStatus='';
function today(){return Domain.iso(new Date());}
function vacationStats(id){return Domain.vacation(db,id,view.year||new Date().getFullYear());}
function workdays(a,b){return Domain.days(a,b).filter(d=>Domain.working(d,db)).length;}
async function request(path,body,method='POST'){const r=await fetch(path,{method:body?method:'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||'Anfrage fehlgeschlagen'),{status:r.status});return data;}
function acceptState(x){db=x.state;revision=x.revision;confirmed=Domain.clone(db);}
async function load(){try{acceptState(await request('/api/state'));render();}catch(e){db={session:null,users:[]};renderLogin();if(e.status!==401)toast(e.message,'err');}}
async function save(){if(saving)throw Error('Speicherung läuft bereits.');saving=true;document.body.classList.add('saving');try{const next=await request('/api/state',{revision,state:db},'PUT');acceptState(next);dirty=false;}catch(e){db=Domain.clone(confirmed);toast(e.message,'err');throw e;}finally{saving=false;document.body.classList.remove('saving');}}
async function audit(){/* Server creates the immutable audit entry in the same transaction. */}
function renderLogin(){document.getElementById('app').innerHTML='<div class="login-screen"><form class="login-card" onsubmit="login(event)"><div class="login-logo">ION</div><h1>ION BAU</h1><p>Dein Team. Deine Baustellen.</p><div class="field"><label for="loginEmail">E-Mail</label><input id="loginEmail" type="email" autocomplete="username" required></div><div class="field mt12"><label for="loginPass">Passwort</label><input id="loginPass" type="password" autocomplete="current-password" required></div><button class="btn primary w100 mt16">Anmelden</button><p class="small mt16">Zugang erhältst du von deiner Geschäftsführung.</p></form></div>';}
async function login(e){e.preventDefault();try{acceptState(await request('/api/state',{action:'login',email:v('loginEmail'),password:document.getElementById('loginPass').value}));view.page='dashboard';render();}catch(e){toast(e.message,'err');}}
async function logout(){if(!discard())return;await request('/api/state',{action:'logout'});drafts.clear();cleanup();confirmed=null;db={session:null,users:[]};renderLogin();}
function activeProjects(){return db.projects.filter(p=>!p.archived&&p.status!=='Abgeschlossen'&&canProject(p));}
function stopVoice(){if(mediaRecorder?.state==='recording'){mediaRecorder.onstop=null;mediaRecorder.stop();mediaRecorder.stream?.getTracks().forEach(t=>t.stop());}mediaRecorder=null;}
function cleanup(){modalToken++;materialPending=null;absencePending=null;pendingLogo=null;stopVoice();}
function discard(){return !dirty||confirm('Ungespeicherte Änderungen verwerfen?');}
function closeModal(force=false){if(!force&&!discard())return false;cleanup();dirty=false;document.body.classList.remove('modal-open');document.getElementById('modalRoot').innerHTML='';document.getElementById('app').inert=false;returnFocus?.focus?.();return true;}
function openModal(title,body,foot='',wide=false){if(!closeModal())return;returnFocus=document.activeElement;document.body.classList.add('modal-open');document.getElementById('app').inert=true;const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="modal-head"><h2 id="modalTitle">${title}</h2><button class="xbtn" aria-label="Dialog schließen" onclick="closeModal()">×</button></div><div class="modal-body">${body}</div><div class="modal-foot">${foot}</div></section></div>`;root.querySelector('input,select,textarea,button')?.focus();root.oninput=()=>{dirty=true;};labelFields(root);}
function labelFields(root){root.querySelectorAll('.field').forEach((f,i)=>{const l=f.querySelector('label'),input=f.querySelector('input,select,textarea');if(l&&input){input.id ||= 'field_'+i+'_'+modalToken;l.htmlFor=input.id;}});}
function rememberChat(){const el=document.getElementById('chatText');if(el&&view.projectId)drafts.set(user().id+':'+view.projectId,{text:el.value,attachments:chatPending.slice()});stopVoice();}
function route(){const params=new URLSearchParams({page:view.page});if(view.projectId)params.set('project',view.projectId);if(view.projectTab)params.set('tab',view.projectTab);history.pushState(null,'','#'+params);}
function go(p){if(!discard())return;rememberChat();closeModal(true);view.page=p;view.projectId=null;view.selectedFolder=null;route();render();}
function openProject(id,tab='overview'){if(!discard())return;rememberChat();closeModal(true);view.page='project';view.projectId=id;view.projectTab=tab;view.selectedFolder=null;route();render();}
function setProjectTab(t){rememberChat();view.projectTab=t;view.selectedFolder=null;route();render();}
window.addEventListener('popstate',()=>{rememberChat();closeModal(true);readRoute();render();});
function readRoute(){const p=new URLSearchParams(location.hash.slice(1));view.page=p.get('page')||'dashboard';view.projectId=p.get('project');view.projectTab=p.get('tab')||'overview';}
window.addEventListener('beforeunload',e=>{if(dirty||saving||document.getElementById('chatText')?.value){e.preventDefault();e.returnValue='';}});
window.addEventListener('unhandledrejection',e=>{e.preventDefault();toast(e.reason?.message||'Aktion fehlgeschlagen','err');});
document.addEventListener('keydown',e=>{const modal=document.querySelector('.modal');if(e.key==='Escape'){if(modal)closeModal();else document.getElementById('sidebar')?.classList.remove('open');}if(modal&&e.key==='Tab'){const list=[...modal.querySelectorAll('button,a[href],input,select,textarea')].filter(x=>!x.disabled&&!x.hidden);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
const renderBase=render;render=function(){renderBase();document.querySelectorAll('.table').forEach(table=>{const heads=[...table.querySelectorAll('th')].map(x=>x.textContent);table.querySelectorAll('tbody tr').forEach(tr=>[...tr.children].forEach((td,i)=>td.dataset.label=heads[i]||'Aktion'));});labelFields(document.getElementById('app'));document.querySelector('.hamburger')?.setAttribute('aria-label','Menü öffnen');document.querySelector('.sidebar')?.insertAdjacentHTML('afterbegin','<button class="btn mobile-only" onclick="toggleSidebar()">Menü schließen</button>');if(view.page==='project'){const id=user()?.id+':'+view.projectId,d=drafts.get(id)||{text:'',attachments:[]};chatPending=d.attachments;const el=document.getElementById('chatText');if(el){el.value=d.text;el.addEventListener('input',()=>drafts.set(id,{text:el.value,attachments:chatPending.slice()}));drawPending();const p=project(view.projectId);el.insertAdjacentHTML('afterend',`<select aria-label="Person erwähnen" onchange="insertMention(this.value);this.value='' "><option value="">@ Person</option>${p.members.map(id=>`<option value="${id}">${esc(userName(id))}</option>`).join('')}</select>`);}}};
const navBase=navItems;navItems=function(){const out=navBase();if(!isOffice())out.splice(2,0,['planning','Meine Planung','planning']);return out;};
const mobileBase=mobileNav;mobileNav=function(){return mobileBase().replace("['me','Mehr'","['me','Mein Bereich'").replace('>Mehr<','>Mein Bereich<');};
const brandBase=companyBrand;companyBrand=function(){return brandBase().replaceAll('Unternehmen einrichten',isAdmin()?'Unternehmen einrichten':'ION BAU');};
const projectBase=projectPage;projectPage=function(){const p=project(view.projectId);let html=projectBase();if(p&&isOffice())html=`<div class="actions mb16"><button class="btn" onclick="toggleArchive('${p.id}')">${p.archived?'Reaktivieren':'Archivieren'}</button></div>`+html;return html;};
const docsBase=projectDocs;projectDocs=function(p){if(view.selectedFolder&&!isOffice()&&!p.folders.some(f=>f.id===view.selectedFolder&&f.employeeVisible))return '<p>Kein Zugriff auf diesen Ordner.</p>';return docsBase(p).replace(/<div class="folder" onclick=/g,'<div class="folder" role="button" tabindex="0" onkeydown="if(event.key===\'Enter\'||event.key===\' \'){event.preventDefault();this.click()}" onclick=').replace(/>Öffnen<\/a>/g,'>Herunterladen</a>');};
function overtimeTotal(id){const closed=db.monthClosures.filter(c=>c.userId===id).reduce((n,c)=>n+c.balance,0);return closed;}
function monthlyActual(id,m){const closed=db.monthClosures.find(c=>c.userId===id&&c.month===m);if(closed)return closed.actual;return db.timeEntries.filter(t=>t.userId===id&&t.date.startsWith(m)).reduce((n,t)=>n+t.hours,0)+Domain.credits(db,id,m);}
function timesPage(){const m=view.month||monthKey(),emps=db.users.filter(u=>u.active&&(isOffice()?u.role==='employee':u.id===user().id));return `${pageHead('Zeiterfassung','Gebuchte Stunden und Abwesenheitsgutschriften',`<button class="btn primary" onclick="timeForm()">Stunden erfassen</button>`)}<div class="filters"><label>Monat <input type="month" value="${m}" onchange="view.month=this.value;render()"></label>${isOffice()?'<button class="btn" onclick="exportTimesCSV()">Auswahl als CSV</button>':''}</div><div class="grid three-col">${emps.map(u=>`<div class="card pad"><h3>${esc(userName(u.id))}</h3><p>Soll: ${getTarget(u.id,m)} h · Ist inkl. Gutschrift: ${fmtNum(monthlyActual(u.id,m))} h</p><p>Monatssaldo: ${fmtNum(monthlyActual(u.id,m)-getTarget(u.id,m))} h</p><p>Abgeschlossene Überstunden: ${fmtNum(overtimeTotal(u.id))} h</p>${isOffice()?`<button class="btn sm" onclick="targetForm('${u.id}','${m}')">Soll ändern</button>`:''}</div>`).join('')}</div>${timeTable(db.timeEntries.filter(t=>t.date.startsWith(m)&&(isOffice()||t.userId===user().id)))}${isOffice()?`<div class="actions mt16"><button class="btn" onclick="closeMonth('${m}')">Monat abschließen</button><button class="btn" onclick="reopenMonth('${m}')">Abschluss wieder öffnen</button></div>`:''}`;}
const timeBase=timeTable;timeTable=function(arr){let html=timeBase(arr);html=html.replace('</thead>','</thead>');const doc=document.createElement('template');doc.innerHTML=html;doc.content.querySelector('thead tr')?.insertAdjacentHTML('beforeend','<th>Aktion</th>');doc.content.querySelectorAll('tbody tr').forEach((tr,i)=>{const t=arr[i];if(t&&!isMonthClosed(t.userId,monthKey(t.date)))tr.insertAdjacentHTML('beforeend',`<td><button class="btn sm" onclick="editTime('${t.id}')">Korrigieren</button><button class="btn sm danger" onclick="removeEntry('timeEntries','${t.id}')">Entfernen</button></td>`);});return doc.innerHTML;};
const timeFormBase=timeForm;timeForm=function(pid=null){editingTime=null;timeFormBase(pid);};
function editTime(id){const t=db.timeEntries.find(x=>x.id===id);timeForm(t.projectId);editingTime=id;for(const [key,val]of Object.entries({timeUser:t.userId,timeDate:t.date,timeHours:t.hours,timeActivity:t.activity,timeNote:t.note}))document.getElementById(key).value=val||'';}
async function saveTime(){const t={id:editingTime||uid('te'),userId:v('timeUser'),date:v('timeDate'),hours:Number(v('timeHours')),projectId:v('timeProject'),activity:v('timeActivity'),note:v('timeNote')};if(isMonthClosed(t.userId,monthKey(t.date)))return toast('Monat zuerst wieder öffnen.','err');if(editingTime)db.timeEntries=db.timeEntries.filter(x=>x.id!==editingTime);db.timeEntries.push(t);await save();closeModal(true);render();toast('Stunden gespeichert');}
async function removeEntry(table,id){if(!confirm('Eintrag entfernen? Die Änderung bleibt im Verlauf nachvollziehbar.'))return;db[table]=db[table].filter(x=>x.id!==id);await save();render();toast('Eintrag entfernt');}
async function closeMonth(m){if(!isOffice())return;const missing=db.allocations.filter(a=>a.date.startsWith(m)&&!Domain.absent(db,a.userId,a.date)&&!db.timeEntries.some(t=>t.userId===a.userId&&t.date===a.date));if(missing.length&&!confirm(`${missing.length} Einsatztage ohne Stunden. Trotzdem abschließen?`))return;for(const u of db.users.filter(u=>u.active&&u.role==='employee'))if(!isMonthClosed(u.id,m))db.monthClosures.push({id:uid('mc'),userId:u.id,month:m,target:getTarget(u.id,m),actual:monthlyActual(u.id,m),balance:monthlyActual(u.id,m)-getTarget(u.id,m)});await save();render();}
async function reopenMonth(m){if(!isOffice()||!confirm('Monat '+m+' zur Korrektur wieder öffnen?'))return;db.monthClosures=db.monthClosures.filter(c=>c.month!==m);await save();render();}
function exportTimesCSV(){const arr=db.timeEntries.filter(t=>t.date.startsWith(view.month||monthKey())&&(isOffice()||t.userId===user().id));const rows=[['Datum','Mitarbeiter','Projekt','Stunden','Tätigkeit','Notiz'],...arr.map(t=>[t.date,userName(t.userId),project(t.projectId)?.name||'',t.hours,t.activity||'',t.note||''])];const safe=x=>{let s=String(x);if(/^[\s]*[=+@-]/.test(s)&&typeof x!=='number')s="'"+s;return '"'+s.replaceAll('"','""')+'"';};downloadBlob('ION_BAU_'+(view.month||monthKey())+'.csv','text/csv;charset=utf-8','\ufeff'+rows.map(r=>r.map(safe).join(';')).join('\r\n'));}
async function saveTarget(id,m){if(isMonthClosed(id,m))return toast('Monat zuerst wieder öffnen.','err');db.monthlyTargets[id+'_'+m]=Number(v('targetVal'));await save();closeModal(true);render();}
const allocationBase=allocationForm;allocationForm=function(){editingAllocation=null;allocationBase();};
function editAllocation(id){const a=db.allocations.find(x=>x.id===id);allocationForm();editingAllocation=id;document.querySelectorAll('.allocUser').forEach(x=>{x.checked=x.value===a.userId;x.disabled=true;});for(const [key,val]of Object.entries({allocProject:a.projectId,allocDate:a.date,allocHours:a.hours,allocNote:a.note}))document.getElementById(key).value=val;}
async function saveAllocation(){const ids=[...document.querySelectorAll('.allocUser:checked')].map(x=>x.value),date=v('allocDate'),hours=Number(v('allocHours')),pid=v('allocProject');if(!ids.length)return toast('Mitarbeiter auswählen','err');Domain.range(date,date);for(const id of ids){if(Domain.absent(db,id,date))return toast('Mitarbeiter ist abwesend. Abwesenheit zuerst klären.','err');const total=db.allocations.filter(a=>a.id!==editingAllocation&&a.userId===id&&a.date===date).reduce((n,a)=>n+a.hours,0)+hours;if(total>8&&!confirm(`${userName(id)}: ${total} Stunden an diesem Tag einplanen?`))return;if(!project(pid)?.members.includes(id))return toast('Mitarbeiter zuerst unter Projekt → Mitarbeiter zuordnen.','err');}if(editingAllocation)db.allocations=db.allocations.filter(a=>a.id!==editingAllocation);for(const id of ids)db.allocations.push({id:editingAllocation||uid('a'),userId:id,projectId:pid,date,hours,note:v('allocNote')});await save();closeModal(true);render();}
function planCell(id,d){const abs=db.absences.filter(a=>a.userId===id&&['Genehmigt','Gemeldet'].includes(a.status)&&a.start<=d&&a.end>=d);const entries=db.allocations.filter(a=>a.userId===id&&a.date===d);return abs.map(a=>`<div class="allocation absence-vac">${a.type==='vacation'?'Urlaub':a.type==='sick'?'Krank':'Frei'}</div>`).join('')+entries.map(a=>`<div class="allocation"><b>${esc(project(a.projectId)?.name||'Projekt')}</b><div>${fmtNum(a.hours)} h · ${esc(a.note||'')}</div>${abs.length?'<strong class="warning">Konflikt mit Abwesenheit</strong>':''}${isOffice()?`<div class="actions"><button class="btn sm" onclick="editAllocation('${a.id}')">Ändern</button><button class="btn sm" onclick="removeEntry('allocations','${a.id}')">Entfernen</button></div>`:''}</div>`).join('')||'–';}
const phaseBase=phaseForm;phaseForm=function(){editingPhase=null;phaseBase();};
function editPhase(id){const p=db.phases.find(p=>p.id===id);phaseForm();editingPhase=id;for(const [k,val]of Object.entries({phaseProject:p.projectId,phaseName:p.name,phaseStart:p.start,phaseEnd:p.end,phaseRequired:p.required}))document.getElementById(k).value=val;}
async function savePhase(){const p={id:editingPhase||uid('ph'),projectId:v('phaseProject'),name:v('phaseName'),start:v('phaseStart'),end:v('phaseEnd'),required:Number(v('phaseRequired')),status:'Geplant'};if(editingPhase)db.phases=db.phases.filter(x=>x.id!==editingPhase);db.phases.push(p);await save();closeModal(true);render();}
function phaseRow(ph,w){const p=project(ph.projectId);if(!p||p.archived||p.status==='Abgeschlossen')return '';return `<div class="phase-review"><div class="between"><div><b>${esc(p.name)} · ${esc(ph.name)}</b><p>${fmtDate(ph.start)} – ${fmtDate(ph.end)} · Bedarf ${ph.required} Personen/Tag</p></div><div class="actions"><button class="btn sm" onclick="editPhase('${ph.id}')">Ändern</button><button class="btn sm" onclick="removeEntry('phases','${ph.id}')">Entfernen</button></div></div><div class="week-days">${w.filter(d=>d>=ph.start&&d<=ph.end).map(d=>{const n=Domain.attendance(db,p.id,d),work=Domain.working(d,db);return `<div class="day-box"><b>${fmtDate(d)}</b><span class="pill ${work&&n<ph.required?'orange':'green'}">${n}/${ph.required}${work?'':' · arbeitsfrei'}</span></div>`;}).join('')}</div></div>`;}
const absenceBase=absenceForm;absenceForm=function(type){editingAbsence=null;absenceBase(type);};
function editAbsence(id){const a=db.absences.find(x=>x.id===id);absenceForm(a.type);editingAbsence=id;document.getElementById('absUser').value=a.userId;document.getElementById('absStart').value=a.start;document.getElementById('absEnd').value=a.end;document.getElementById('absNote').value=a.note;absencePending=a.attachment||null;}
async function saveAbsence(type){const id=v('absUser'),start=v('absStart'),end=v('absEnd');Domain.range(start,end);const collisions=db.allocations.filter(a=>a.userId===id&&a.date>=start&&a.date<=end);if(collisions.length&&!confirm(`${collisions.length} geplante Einsätze liegen im Zeitraum. Als Konflikte anzeigen und Abwesenheit trotzdem erfassen?`))return;const old=db.absences.find(a=>a.id===editingAbsence);const a={...old,id:editingAbsence||uid('ab'),userId:id,type,start,end,status:old?.status||(type==='vacation'?(isOffice()?'Genehmigt':'Beantragt'):'Gemeldet'),note:v('absNote'),createdBy:old?.createdBy||user().id,attachment:absencePending};if(editingAbsence)db.absences=db.absences.filter(x=>x.id!==editingAbsence);db.absences.push(a);await save();closeModal(true);render();toast('Abwesenheit gespeichert');}
const absenceTableBase=absenceAdminTable;absenceAdminTable=function(){const html=absenceTableBase();const doc=document.createElement('template');doc.innerHTML=html;const arr=db.absences.filter(a=>isOffice()||a.userId===user().id).sort((a,b)=>b.start.localeCompare(a.start));doc.content.querySelectorAll('tbody tr').forEach((tr,i)=>{const a=arr[i];if(!a)return;const canCancel=isOffice()||['Beantragt','Gemeldet'].includes(a.status);if(canCancel&&a.status!=='Storniert')tr.lastElementChild.insertAdjacentHTML('beforeend',` ${isOffice()?`<button class="btn sm" onclick="editAbsence('${a.id}')">Korrigieren</button>`:''}<button class="btn sm" onclick="cancelAbsence('${a.id}')">Stornieren</button>`);});return doc.innerHTML;};
async function cancelAbsence(id){if(!confirm('Abwesenheit stornieren?'))return;db.absences.find(x=>x.id===id).status='Storniert';await save();render();}
const employeeFormBase=employeeForm;employeeForm=function(id=null){employeeFormBase(id);if(id){const u=db.users.find(x=>x.id===id);document.getElementById('ef_vac').value=u.vacationByYear?.[view.year]??u.vacationAnnual??30;}const p=document.getElementById('ef_pass');if(p){p.type='password';p.autocomplete='new-password';p.minLength=12;}document.querySelector('#ef_vac')?.closest('.field').querySelector('label').replaceChildren(document.createTextNode('Urlaubsanspruch '+view.year));};
async function saveEmployee(id){if(!isAdmin())return;const first=v('ef_first'),last=v('ef_last'),email=v('ef_email'),pass=v('ef_pass');if(!first||!last||!email||(!id&&!pass))return toast('Pflichtfelder fehlen.','err');let u=id?db.users.find(x=>x.id===id):{id:uid('u')};const year=String(view.year);Object.assign(u,{first,last,email,phone:v('ef_phone'),role:v('ef_role'),active:v('ef_active')==='1',entry:v('ef_entry'),vacationAnnual:Number(v('ef_vac')),vacationByYear:{...(u.vacationByYear||{}),[year]:Number(v('ef_vac'))},notes:v('ef_notes')});if(pass)u.password=pass;if(!id)db.users.push(u);await save();closeModal(true);render();toast('Mitarbeiter gespeichert');}
const employeesBase=employeesPage;employeesPage=function(){return `<label>Urlaubsjahr <input type="number" min="2020" max="2100" value="${view.year}" onchange="view.year=Number(this.value);render()"></label>`+employeesBase();};
const taskFormBase=taskForm;taskForm=function(id=null,pid=null,prefill=''){taskFormBase(id,pid,prefill);const select=document.getElementById('tf_project');const filter=()=>{const members=project(select.value)?.members||[];document.querySelectorAll('.taskAss').forEach(el=>{el.disabled=!members.includes(el.value);if(el.disabled)el.checked=false;el.closest('label').hidden=el.disabled;});};select?.addEventListener('change',filter);filter();};
const tasksBase=tasksPage;tasksPage=function(){return tasksBase();};
const detailBase=taskDetail;taskDetail=function(id){const t=db.tasks.find(t=>t.id===id);if(!t||(!isOffice()&&!t.assignees.includes(user().id)))return toast('Kein Zugriff.','err');detailBase(id);const b=[...document.querySelectorAll('.modal button')].find(x=>x.textContent==='Status weiter');if(b){b.textContent=t.status==='Offen'?'Arbeit beginnen':t.status==='In Arbeit'?'Als erledigt markieren':'Erledigt';b.disabled=t.status==='Erledigt';}};
function insertMention(id){const el=document.getElementById('chatText');if(id&&el){el.value+=' @['+id+'] ';el.focus();}}
function linkMentions(text){return text.replace(/@\[([-\w]+)\]/g,(_,id)=>`<b>@${esc(userName(id))}</b>`);}
function drawPending(){if(user()&&view.projectId)drafts.set(user().id+':'+view.projectId,{text:document.getElementById('chatText')?.value||'',attachments:chatPending.slice()});const el=document.getElementById('chatPendingPreview');if(el)el.innerHTML=chatPending.map((a,i)=>`<span>${esc(a.name)} <button class="btn sm" onclick="chatPending.splice(${i},1);drawPending()">Entfernen</button></span>`).join('');}
async function sendChat(pid){const tx=v('chatText');if(!tx&&!chatPending.length)return;db.chat.push({id:uid('m'),projectId:pid,userId:user().id,text:tx,at:new Date().toISOString(),pinned:false,attachments:chatPending.slice()});await save();drafts.delete(user().id+':'+pid);document.getElementById('chatText').value='';chatPending=[];render();document.getElementById('messages')?.scrollTo(0,1e9);}
async function notificationModal(){const arr=db.notifications.filter(n=>n.userId===user().id).slice(0,30);arr.forEach(n=>n.read=true);await save();openModal('Benachrichtigungen',arr.map(n=>`<div class="list-row"><span>${esc(n.text)}</span>${n.projectId?`<button class="btn" onclick="closeModal(true);openProject('${n.projectId}','chat')">Zum Chat</button>`:''}</div>`).join('')||'Keine neuen Benachrichtigungen.');}
async function uploadFile(file){if(!file)return null;if(file.size>20*1024*1024)throw Error('Datei maximal 20 MB.');const {id}=await request('/api/file',{action:'start',name:file.name,mime:file.type||'application/octet-stream'});for(let offset=0;offset<file.size;offset+=1024*1024){const bytes=new Uint8Array(await file.slice(offset,offset+1024*1024).arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));await request('/api/file',{action:'chunk',id,offset,data:btoa(text)});}return await request('/api/file',{action:'finish',id});}
async function fileToAttachment(file,cb){if(!file)return;const token=modalToken;const a=await uploadFile(file);if(token===modalToken)await cb(a);}
async function uploadDoc(pid,fid,file){const token=modalToken;const a=await uploadFile(file);if(!a||token!==modalToken)return;project(pid).folders.find(f=>f.id===fid).files.push(a);await save();render();toast('Datei gespeichert');}
async function addChatFiles(files){const pid=view.projectId,person=user().id;for(const f of files){const a=await uploadFile(f);if(view.projectId!==pid||user()?.id!==person)return;chatPending.push(a);drawPending();}}
async function previewCompanyLogo(file){if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('PNG, JPG oder WebP auswählen.','err');const token=modalToken,a=await uploadFile(file);if(token!==modalToken)return;pendingLogo=a.data;document.getElementById('logoPreview').innerHTML=`<img alt="Logo-Vorschau" src="${pendingLogo}&preview=1" style="max-width:190px;max-height:100px">`;}
async function toggleVoiceRecord(){if(mediaRecorder?.state==='recording'){mediaRecorder.stop();return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return toast('Sprachaufnahme hier nicht verfügbar.','err');try{const pid=view.projectId,person=user().id,stream=await navigator.mediaDevices.getUserMedia({audio:true});if(view.projectId!==pid){stream.getTracks().forEach(t=>t.stop());return;}mediaChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>mediaChunks.push(e.data);mediaRecorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());document.getElementById('voiceBtn')?.replaceChildren(document.createTextNode('Aufnahme'));if(view.projectId!==pid||user()?.id!==person)return;const blob=new Blob(mediaChunks,{type:mediaRecorder.mimeType});const file=new File([blob],'Sprachnachricht.'+(blob.type.includes('mp4')?'m4a':'webm'),{type:blob.type});const a=await uploadFile(file);chatPending.push(a);drawPending();};mediaRecorder.start();document.getElementById('voiceBtn').textContent='Stop';}catch(e){toast('Mikrofonzugriff nicht möglich.','err');}}
const matFormBase=materialForm;materialForm=function(id=null,pid=null,prefill=''){matFormBase(id,pid,prefill);const m=db.materials.find(x=>x.id===id);materialPending=m?.attachment||null;if(isOffice()){const select=document.getElementById('matStatus');if(![...select.options].some(x=>x.value==='Teilgeliefert'))select.add(new Option('Teilgeliefert','Teilgeliefert'));if(m)select.value=m.status;document.querySelectorAll('.mat-line').forEach((row,i)=>row.insertAdjacentHTML('beforeend',`<label class="received-field">Geliefert <input class="matReceived" type="number" min="0" step="0.01" value="${m?.items[i]?.received??0}"></label>`));}};
const matSaveBase=saveMaterial;saveMaterial=async function(id){const inputs=[...document.querySelectorAll('.matName')],qty=[...document.querySelectorAll('.matQty')],units=[...document.querySelectorAll('.matUnit')],rec=[...document.querySelectorAll('.matReceived')];let m=id?db.materials.find(x=>x.id===id):{id:uid('mr'),requestedBy:user().id,createdAt:new Date().toISOString(),status:'Angefordert',supplier:'',delivery:'',orderNo:'',officeNote:''};if(!isOffice()&&id&&(m.requestedBy!==user().id||m.status!=='Angefordert'))return;Object.assign(m,{projectId:v('matProject'),needed:v('matNeeded'),note:v('matNote'),items:inputs.map((x,i)=>({name:x.value.trim(),qty:Number(qty[i].value),unit:units[i].value,received:Number(rec[i]?.value||0)}))});if(isOffice()){m.status=v('matStatus');m.supplier=v('matSupplier');m.delivery=v('matDelivery');m.orderNo=v('matOrder');m.officeNote=v('matOffice');if(m.status==='Geliefert')m.items.forEach(i=>i.received=i.qty);}if(materialPending)m.attachment=materialPending;if(!id)db.materials.push(m);await save();closeModal(true);render();};
const matDetailBase=materialDetail;materialDetail=function(id){matDetailBase(id);const m=db.materials.find(x=>x.id===id);document.querySelector('.modal-body').insertAdjacentHTML('beforeend',`<div class="card pad mt16"><b>Lieferdatum: ${fmtDate(m.delivery)}</b><p>${isOffice()?esc(m.officeNote||'Keine Büro-Notiz'):''}</p>${m.items.map(i=>`<p>${esc(i.name)}: ${fmtNum(i.received||0)} / ${fmtNum(i.qty)} ${esc(i.unit)} geliefert</p>`).join('')}</div>`);if(!isOffice()&&m.requestedBy===user().id&&m.status==='Angefordert')document.querySelector('.modal-foot').insertAdjacentHTML('beforeend',`<button class="btn" onclick="materialForm('${id}')">Korrigieren</button>`);};
function materialsPage(){let arr=db.materials.filter(m=>isOffice()||project(m.projectId)?.members.includes(user().id));if(view.materialStatus)arr=arr.filter(m=>m.status===view.materialStatus);return `${pageHead('Material','Anforderungen und Lieferungen',`<button class="btn primary" onclick="materialForm()">Material anfordern</button>`)}<div class="filters">${['','Angefordert','Bestellt','Unterwegs','Teilgeliefert','Geliefert','Storniert'].map(s=>`<button class="filter ${view.materialStatus===s?'active':''}" onclick="view.materialStatus='${s}';render()">${s||'Alle'}</button>`).join('')}</div>${materialTable(arr)}`;}
const searchBase=searchPage;searchPage=function(){const q=view.search.toLowerCase(),html=searchBase();if(!q)return html;const blocks=[['Mitarbeiter',db.users.filter(u=>[u.first,u.last,u.email,u.phone].some(x=>String(x||'').toLowerCase().includes(q))).map(u=>`<p><b>${esc(userName(u.id))}</b>${contactLinks(u.phone,u.email)}</p>`)],['Material',db.materials.filter(m=>m.items.some(i=>i.name.toLowerCase().includes(q))).map(m=>`<button class="btn" onclick="materialDetail('${m.id}')">${esc(project(m.projectId)?.name||'')} · ${esc(m.items[0]?.name)}</button>`)],['Chat',db.chat.filter(m=>m.text.toLowerCase().includes(q)).map(m=>`<p><button class="btn" onclick="openProject('${m.projectId}','chat')">${esc(project(m.projectId)?.name||'')}</button> ${esc(m.text)}</p>`)]];return html+blocks.map(([title,items])=>`<section class="card pad mt16"><h2>${title}</h2>${items.join('')||'Keine Treffer'}</section>`).join('');};
function dashboard(){const ps=activeProjects(),tasks=db.tasks.filter(t=>t.status!=='Erledigt'&&(isOffice()||t.assignees.includes(user().id))),mats=db.materials.filter(m=>!['Geliefert','Storniert'].includes(m.status));const rows=ps.filter(p=>isOffice()||db.allocations.some(a=>a.projectId===p.id&&a.userId===user().id&&a.date===today()));const absent=Domain.absent(db,user().id,today());return `${pageHead(isOffice()?'Dashboard':'Mein Tag',fmtDate(today()))}${!db.company.name&&isAdmin()?'<div class="card pad mb16">Bitte zuerst dein Unternehmen einrichten. <button class="btn" onclick="go(\'settings\')">Einstellungen öffnen</button></div>':''}<div class="grid three-col"><div class="card kpi"><div class="label">Aktive Projekte</div><div class="num">${ps.length}</div></div><div class="card kpi"><div class="label">Offene Aufgaben</div><div class="num">${tasks.length}</div></div><div class="card kpi"><div class="label">Offenes Material</div><div class="num">${mats.length}</div></div></div><div class="grid two-col mt16"><section class="card pad"><h2>Heute auf den Baustellen</h2>${absent?'<p class="warning">Für dich ist heute eine Abwesenheit erfasst.</p>':''}${rows.map(p=>{const phases=db.phases.filter(ph=>ph.projectId===p.id&&ph.start<=today()&&ph.end>=today());const n=Domain.attendance(db,p.id,today());return `<div class="list-row"><div><b>${esc(p.name)}</b><p>${n} verfügbare Personen</p>${phases.map(ph=>`<div class="${n<ph.required?'warning':''}">${esc(ph.name)}: ${n}/${ph.required}</div>`).join('')}</div><button class="btn" onclick="openProject('${p.id}')">Öffnen</button></div>`;}).join('')||'Keine persönlichen Einsätze heute.'}</section><section class="card pad"><h2>Handlungsbedarf</h2>${overdueTasks().map(t=>`<p><button class="btn" onclick="taskDetail('${t.id}')">${esc(t.title)}</button> ${fmtDate(t.due)}</p>`).join('')}${mats.filter(m=>m.needed<=today()).map(m=>`<p><button class="btn" onclick="materialDetail('${m.id}')">Material benötigt: ${esc(project(m.projectId)?.name||'')}</button></p>`).join('')}${isOffice()?missingTimeWarnings():''}</section><section class="card pad"><h2>Meine Aufgaben</h2>${tasks.filter(t=>t.assignees.includes(user().id)).map(t=>`<p><button class="btn" onclick="taskDetail('${t.id}')">${esc(t.title)}</button></p>`).join('')||'Keine offenen Aufgaben.'}</section><section class="card pad"><h2>Diese Woche</h2><button class="btn" onclick="go('planning')">${isOffice()?'Mitarbeiterplanung':'Meine Planung'}</button></section></div>`;}
const settingsBase=settingsPage;settingsPage=function(){if(!isAdmin())return 'Kein Zugriff.';return settingsBase().replace(/<button class="btn danger" onclick="resetDemo\(\)">Testdaten zurücksetzen<\/button>/,'').replace('Für die lokale Testversion kannst du alle Daten als JSON sichern und wieder importieren.','Sicherung ohne Passwörter und Sitzung. Vor jedem Import wird der aktuelle Stand serverseitig gesichert.')+`<section class="card pad mt16"><h2>Arbeitskalender</h2><p>Feiertage Hessen; Urlaub und Krankheit werden mit Tagesstunden gutgeschrieben. Bereits gebuchte Stunden desselben Tages werden angerechnet.</p><label>Gutschrift je Arbeitstag <input type="number" id="creditHours" min="0" max="24" step="0.25" value="${db.company.creditHours??8}"></label><label>Zusätzliche arbeitsfreie Tage (je Zeile JJJJ-MM-TT)<textarea id="extraHolidays">${esc((db.company.extraHolidays||[]).join('\n'))}</textarea></label><button class="btn" onclick="saveCalendar()">Kalender speichern</button></section><section class="card pad mt16"><h2>Änderungsverlauf</h2>${db.audit.slice(0,100).map(x=>`<p>${esc(x.at)} · ${esc(userName(x.userId))} · ${esc(x.entity)} · ${esc(x.action)}</p>`).join('')}</section>`;};
async function saveCalendar(){const n=Number(v('creditHours'));if(!Number.isFinite(n)||n<0||n>24)return toast('Tagesstunden zwischen 0 und 24 eingeben.','err');const dates=v('extraHolidays').split(/\s+/).filter(Boolean);if(dates.some(d=>!Domain.validDate(d)))return toast('Datumsformat JJJJ-MM-TT verwenden.','err');db.company.creditHours=n;db.company.extraHolidays=dates;await save();render();}
function exportBackup(){if(!isAdmin())return;const copy=Domain.clone(db);delete copy.session;copy.users.forEach(u=>{delete u.password;delete u.passwordHash;});downloadBlob('ION_BAU_Backup_'+today()+'.json','application/json',JSON.stringify({format:'ion-bau',version:2,state:copy},null,2));}
async function importBackup(file){if(!isAdmin()||!file)return;try{const data=JSON.parse(await file.text());if(data.format!=='ion-bau'||data.version!==2)throw Error('Bitte eine ION BAU Sicherung der Version 2 auswählen. Alte lokale Backups benötigen eine Migration.');const candidate=data.state;candidate.session=db.session;candidate.users.forEach(u=>{delete u.password;delete u.passwordHash;});Domain.validate(candidate);if(candidate.users.some(u=>!db.users.some(x=>x.id===u.id)))throw Error('Benutzerzugänge zuerst anlegen; Backup darf keine unbekannten Benutzer einführen.');if(!confirm(`${candidate.projects.length} Projekte und ${candidate.timeEntries.length} Stundenbuchungen wiederherstellen? Aktueller Stand wird gesichert.`))return;db=candidate;await save();render();toast('Sicherung wiederhergestellt');}catch(e){toast(e.message,'err');}}
function resetDemo(){toast('Zurücksetzen ist im gemeinsamen System nicht verfügbar.','err');}
async function boot(){if('serviceWorker'in navigator){for(const reg of await navigator.serviceWorker.getRegistrations())await reg.unregister();if('caches'in window)for(const key of await caches.keys())if(key.startsWith('ionbau-'))await caches.delete(key);}await load();if(db.session){readRoute();render();}setInterval(async()=>{if(!db.session||saving||dirty||document.querySelector('.modal')||document.getElementById('chatText')?.value)return;try{const x=await request('/api/state');if(x.revision!==revision){acceptState(x);render();}}catch(e){if(e.status===401){db.session=null;renderLogin();}}},15000);}
document.addEventListener('input',e=>{if(view.page==='settings'&&e.target.matches('input,textarea,select'))dirty=true;});
boot();
// Full project list remains available when a project is completed but not archived.
const projectsPageBase=projectsPage;
projectsPage=function(){let html=projectsPageBase();const completed=db.projects.filter(p=>!p.archived&&p.status==='Abgeschlossen'&&canProject(p));if(completed.length)html+=`<section class="card pad mt16"><h2>Abgeschlossene Projekte</h2>${completed.map(p=>`<p><button class="btn" onclick="openProject('${p.id}')">${esc(p.name)}</button></p>`).join('')}</section>`;return html;};
const modalBase=openModal;openModal=function(...args){modalBase(...args);addFilePreviews(document.getElementById('modalRoot'));};
function addFilePreviews(root){root?.querySelectorAll('a[href^="/api/file?id="]').forEach(a=>{if(a.dataset.previewAdded)return;a.dataset.previewAdded='1';const p=document.createElement('a');p.className='btn sm';p.href=a.getAttribute('href')+'&preview=1';p.target='_blank';p.rel='noopener';p.textContent='Vorschau';a.after(p);});}
const renderPreviews=render;render=function(){renderPreviews();addFilePreviews(document.getElementById('app'));};
