const D=require('../domain.js');
const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const deny=()=>{throw Object.assign(Error('Keine Berechtigung für diese Änderung.'),{status:403})};
const omit=(x,keys)=>Object.fromEntries(Object.entries(x).filter(([k])=>!keys.includes(k)));
function visible(s,u){const office=['admin','office'].includes(u.role);const out=D.clone(s);out.session={userId:u.id};out.users=s.users.filter(x=>office||x.id===u.id||s.projects.some(p=>p.members.includes(u.id)&&p.members.includes(x.id))).map(x=>office||x.id===u.id?omit(x,['password','passwordHash']):{id:x.id,first:x.first,last:x.last,email:x.email,phone:x.phone,role:x.role,active:x.active,vacationAnnual:0,entry:''});out.projects=out.projects.filter(p=>office||(!p.archived&&p.members.includes(u.id))).map(p=>({...p,folders:p.folders.filter(f=>office||f.employeeVisible)}));const ids=new Set(out.projects.map(p=>p.id));if(!office){out.tasks=out.tasks.filter(t=>ids.has(t.projectId)&&t.assignees.includes(u.id));out.chat=out.chat.filter(t=>ids.has(t.projectId));out.materials=out.materials.filter(t=>ids.has(t.projectId)).map(t=>omit(t,['officeNote','supplier','orderNo']));for(const key of ['timeEntries','absences','allocations','monthClosures'])out[key]=out[key].filter(x=>x.userId===u.id);out.phases=out.phases.filter(x=>ids.has(x.projectId));out.monthlyTargets=Object.fromEntries(Object.entries(out.monthlyTargets).filter(([k])=>k.startsWith(u.id+'_')));out.audit=[];}out.notifications=out.notifications.filter(x=>x.userId===u.id);return out;}
function merge(s,u,incoming){const before=visible(s,u),next=D.clone(s),office=['admin','office'].includes(u.role),admin=u.role==='admin';const userIds=new Set(s.users.map(x=>x.id));
const canP=id=>s.projects.some(p=>p.id===id&&!p.archived&&(office||p.members.includes(u.id)));
const appendOwn=(old,arr,key)=>Array.isArray(arr)&&arr.length>=old.length&&eq(arr.slice(0,old.length),old)&&arr.slice(old.length).every(x=>x[key]===u.id);
for(const key of Object.keys(before)){if(['session','audit'].includes(key))continue;if(eq(before[key],incoming[key]))continue;
if(key==='company'){if(!admin)deny();next.company=incoming.company;continue;}
if(key==='monthlyTargets'){if(!office)deny();for(const c of s.monthClosures)if(!eq(before[key][c.userId+'_'+c.month],incoming[key]?.[c.userId+'_'+c.month]))throw Error('Abgeschlossenen Monat erst wieder öffnen.');next[key]=incoming[key];continue;}
if(!Array.isArray(before[key])||!Array.isArray(incoming[key]))deny();
const oldMap=new Map(before[key].map(x=>[x.id,x])),newMap=new Map(incoming[key].map(x=>[x.id,x]));if(newMap.size!==incoming[key].length)deny();
for(const id of new Set([...oldMap.keys(),...newMap.keys()])){const a=oldMap.get(id),b=newMap.get(id);if(eq(a,b))continue;const original=s[key].find(x=>x.id===id);if(!a&&original)deny();
if(key==='users'){if(!admin)deny();if(id===u.id&&(!b||!b.active||b.role!=='admin'))throw Error('Eigenen Adminzugang nicht sperren.');if(b&&(b.passwordHash||(!a&&!b.password)))deny();}
else if(key==='notifications'){if(!a||!b||!eq(omit(a,['read']),omit(b,['read']))||b.read!==true)deny();}
else if(key==='monthClosures'){if(!office)deny();if(b){if(!/^\d{4}-\d{2}$/.test(b.month))deny();const end=new Date(Number(b.month.slice(0,4)),Number(b.month.slice(5,7)),0,12);if(D.iso(end)>=D.iso(new Date()))throw Error('Nur abgelaufene Monate abschließen.');const actual=s.timeEntries.filter(t=>t.userId===b.userId&&t.date.startsWith(b.month)).reduce((n,t)=>n+t.hours,0)+D.credits(s,b.userId,b.month);b.target=s.monthlyTargets[b.userId+'_'+b.month]??176;b.actual=actual;b.balance=actual-b.target;b.closedBy=u.id;b.closedAt=new Date().toISOString();}}
else if(key==='timeEntries'){for(const t of [a,b].filter(Boolean)){if(!office&&t.userId!==u.id)deny();if(!canP(t.projectId))deny();if(s.monthClosures.some(c=>c.userId===t.userId&&c.month===t.date.slice(0,7)))throw Error('Monat abgeschlossen. Erst wieder öffnen.');}}
else if(key==='absences'){if(!office){if((a&&a.userId!==u.id)||(b&&b.userId!==u.id)||!b)deny();if(!a&&((b.type==='vacation'&&b.status!=='Beantragt')||(b.type==='sick'&&b.status!=='Gemeldet')||b.type==='free'))deny();if(a&&(!['Beantragt','Gemeldet'].includes(a.status)||b.status!=='Storniert'||!eq(omit(a,['status']),omit(b,['status']))))deny();}for(const v of [a,b].filter(Boolean))if(s.monthClosures.some(c=>c.userId===v.userId&&v.start.slice(0,7)<=c.month&&v.end.slice(0,7)>=c.month))throw Error('Betroffenen Monat zuerst wieder öffnen.');}
else if(key==='projects'){if(!office){if(!a||!b||!eq(omit(a,['folders']),omit(b,['folders']))||a.folders.length!==b.folders.length)deny();for(const f of b.folders){const old=a.folders.find(x=>x.id===f.id);if(!old||!old.employeeVisible||!eq(omit(old,['files']),omit(f,['files']))||!appendOwn(old.files,f.files,'userId'))deny();}b.folders=original.folders.map(f=>b.folders.find(x=>x.id===f.id)||f);}}
else if(key==='tasks'){if(!office){if(!a||!b||!canP(a.projectId)||!a.assignees.includes(u.id)||!eq(omit(a,['status','comments','attachments','history']),omit(b,['status','comments','attachments','history']))||!appendOwn(a.comments,b.comments,'userId')||!appendOwn(a.attachments,b.attachments,'userId'))deny();b.history=original.history;}}
else if(key==='chat'){if(!canP((b||a).projectId))deny();if(!a){if(!b||b.userId!==u.id||b.pinned)deny();}else if(!office||!b||!eq(omit(a,['pinned']),omit(b,['pinned'])))deny();}
else if(key==='materials'){if(!canP((b||a).projectId))deny();if(!office){if(!b||(!a&&b.requestedBy!==u.id)||(a&&(a.requestedBy!==u.id||a.status!=='Angefordert'))||b.status!=='Angefordert'||['supplier','orderNo','officeNote'].some(k=>b[k]))deny();if(a&&!eq(omit(a,['items','note','needed','attachment']),omit(b,['items','note','needed','attachment'])))deny();if(a)for(const k of ['supplier','officeNote','orderNo'])if(original[k]!==undefined)b[k]=original[k];}if(a&&b){const flow={Angefordert:['Angefordert','Bestellt','Storniert'],Bestellt:['Bestellt','Unterwegs','Teilgeliefert','Geliefert','Storniert'],Unterwegs:['Unterwegs','Teilgeliefert','Geliefert','Storniert'],Teilgeliefert:['Teilgeliefert','Geliefert','Storniert'],Geliefert:['Geliefert'],Storniert:['Storniert']};if(!flow[a.status]?.includes(b.status))throw Error('Ungültiger Materialstatuswechsel.');}}
else if(['allocations','phases'].includes(key)){if(!office)deny();if(key==='allocations'&&b&&D.absent(next,b.userId,b.date))throw Error('Mitarbeiter ist an diesem Tag abwesend.');}else deny();
if(!b)next[key]=next[key].filter(x=>x.id!==id);else{const i=next[key].findIndex(x=>x.id===id);const record=D.clone(b);if(key==='users'&&original?.passwordHash)record.passwordHash=original.passwordHash;if(i<0)next[key].push(record);else next[key][i]=record;}
next.audit.unshift({id:'audit_'+require('node:crypto').randomUUID(),at:new Date().toISOString(),userId:u.id,action:a?(b?'Geändert':'Entfernt'):'Angelegt',entity:key,entityId:id});
if(key==='tasks'&&b){const t=next.tasks.find(t=>t.id===id);t.history=[...(original?.history||[]),{at:new Date().toISOString(),by:u.id,text:a?'Aufgabe aktualisiert: '+Object.keys(b).filter(k=>!['history'].includes(k)&&!eq(a[k],b[k])).join(', '):'Aufgabe angelegt'}];}
if(key==='chat'&&!a&&b){const p=next.projects.find(p=>p.id===b.projectId);for(const id of p.members){const person=next.users.find(x=>x.id===id);if(person&&id!==u.id&&b.text.includes('@['+id+']'))next.notifications.unshift({id:'n_'+require('node:crypto').randomUUID(),userId:id,projectId:p.id,messageId:b.id,text:'Erwähnung im Projekt '+p.name,at:new Date().toISOString(),read:false});}}
}}
D.validate(next);return next;}
module.exports={visible,merge};
