const {transaction}=require('../server/storage.cjs');
const {visible,merge}=require('../server/policy.cjs');
const {digest,hash,verify,randomBytes}=require('../server/auth.cjs');
module.exports=async(req,res)=>{res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');try{
const body=req.body||{};const action=body.action;const unsafe=req.method!=='GET';if(unsafe){const host=req.headers.host;if(!req.headers.origin||new URL(req.headers.origin).host!==host)return res.status(403).json({error:'Ungültiger Ursprung.'});if(!String(req.headers['content-type']).startsWith('application/json'))return res.status(415).json({error:'JSON erforderlich.'});}
if(!['GET','POST','PUT'].includes(req.method))return res.status(405).end();
const result=await transaction(async c=>{const row=(await c.query('SELECT * FROM ion_state WHERE id=1 FOR UPDATE')).rows[0];if(!row)throw Object.assign(Error('Ersteinrichtung erforderlich.'),{status:503});const s=row.data;
const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('ion_session='))?.slice(12)||'';
if(action==='login'){const key=digest(String(body.email||'').toLowerCase());const attempts=await c.query("INSERT INTO ion_attempts VALUES ($1,1,now()) ON CONFLICT (key) DO UPDATE SET attempts=CASE WHEN ion_attempts.window_start < now()-interval '15 minutes' THEN 1 ELSE ion_attempts.attempts+1 END, window_start=CASE WHEN ion_attempts.window_start < now()-interval '15 minutes' THEN now() ELSE ion_attempts.window_start END RETURNING attempts",[key]);if(attempts.rows[0].attempts>10)return {status:429,error:'Zu viele Versuche. Bitte 15 Minuten warten.'};const u=s.users.find(x=>x.active&&x.email.toLowerCase()===String(body.email||'').toLowerCase());if(!u||typeof body.password!=='string'||body.password.length>256||!verify(body.password,u.passwordHash))return {status:401,error:'Anmeldung nicht gültig.'};await c.query('DELETE FROM ion_attempts WHERE key=$1',[key]);const t=randomBytes(32).toString('hex');await c.query("INSERT INTO ion_sessions VALUES ($1,$2,now()+interval '8 hours')",[digest(t),u.id]);res.setHeader('Set-Cookie',`ion_session=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.VERCEL?'; Secure':''}`);return {state:visible(s,u),revision:row.revision};}
const session=(await c.query('SELECT * FROM ion_sessions WHERE token=$1 AND expires>now()',[digest(token)])).rows[0];const u=session&&s.users.find(x=>x.id===session.user_id&&x.active);if(!u)throw Object.assign(Error('Bitte anmelden.'),{status:401});
if(action==='logout'){await c.query('DELETE FROM ion_sessions WHERE token=$1',[digest(token)]);res.setHeader('Set-Cookie','ion_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return {ok:true};}
if(req.method==='GET')return {state:visible(s,u),revision:row.revision};
if(body.revision!==row.revision)throw Object.assign(Error('Daten wurden inzwischen geändert. Ansicht aktualisieren und Änderung erneut eingeben.'),{status:409});
const next=merge(s,u,body.state);for(const person of next.users){if(person.password){person.passwordHash=hash(person.password);delete person.password;await c.query('DELETE FROM ion_sessions WHERE user_id=$1',[person.id]);}if(!person.active)await c.query('DELETE FROM ion_sessions WHERE user_id=$1',[person.id]);}
// Every file reference must refer to an already accessible file or the actor's new upload.
const oldRefs=new Set(JSON.stringify(visible(s,u)).match(/\/api\/file\?id=[-\w]+/g)||[]);const refs=new Set(JSON.stringify(body.state).match(/\/api\/file\?id=[-\w]+/g)||[]);const allOld=new Set(JSON.stringify(s).match(/\/api\/file\?id=[-\w]+/g)||[]);for(const url of refs){const f=(await c.query('SELECT owner_id,complete FROM ion_files WHERE id=$1',[url.split('=')[1]])).rows[0];if(!f?.complete||(!oldRefs.has(url)&&f.owner_id!==u.id))throw Error('Datei nicht verfügbar.');}
await c.query('INSERT INTO ion_backups(revision,data) VALUES ($1,$2)',[row.revision,s]);await c.query('UPDATE ion_state SET revision=revision+1,data=$1 WHERE id=1',[next]);return {state:visible(next,next.users.find(x=>x.id===u.id)),revision:row.revision+1};});res.status(result.status||200).json(result);
}catch(e){res.status(e.status||400).json({error:e.status===503?e.message:(e.message?.includes('relation')?'Datenbank muss eingerichtet werden.':e.message||'Speichern fehlgeschlagen.')});}};
